import { describe, expect, it } from "vitest";
import { buildMockGameState, MOCK_IDS, mockCardDefinitionsById } from "@/data/mock-card-catalog";
import { applyGameAction } from "@/domain/game/game.reducer";
import { getCardsInZone } from "@/domain/game/game.selectors";

describe("applyGameAction", () => {
  it("draws the first ordered main deck card", () => { const next = applyGameAction(buildMockGameState(), { type: "DRAW_CARD", playerId: MOCK_IDS.local }, mockCardDefinitionsById); expect(next.cardInstances["local-main-1"].zone).toBe("HAND"); expect(getCardsInZone(next, "MAIN_DECK", MOCK_IDS.local)).toHaveLength(1); });
  it("draws essence from the top and preserves deck order", () => { const next = applyGameAction(buildMockGameState(), { type: "DRAW_ESSENCE", playerId: MOCK_IDS.local }, mockCardDefinitionsById); expect(next.cardInstances["local-essence-1"].zone).toBe("ESSENCE_ZONE"); expect(getCardsInZone(next, "ESSENCE_DECK", MOCK_IDS.local)[0].instanceId).toBe("local-essence-2"); });
  it("plays a character and attaches a relic", () => { let next = applyGameAction(buildMockGameState(), { type: "PLAY_CHARACTER", instanceId: "local-hand-char", playerId: MOCK_IDS.local }, mockCardDefinitionsById); next = applyGameAction(next, { type: "PLAY_RELIC", instanceId: "local-hand-relic", playerId: MOCK_IDS.local, attachedToInstanceId: "local-hand-char" }, mockCardDefinitionsById); expect(next.cardInstances["local-hand-char"].zone).toBe("FIELD"); expect(next.cardInstances["local-hand-relic"].attachedToInstanceId).toBe("local-hand-char"); });
  it("moves verse through resolution to graveyard", () => { let next = applyGameAction(buildMockGameState(), { type: "PLAY_VERSE", instanceId: "local-hand-verse", playerId: MOCK_IDS.local }, mockCardDefinitionsById); expect(next.cardInstances["local-hand-verse"].zone).toBe("VERSE_RESOLUTION"); next = applyGameAction(next, { type: "RESOLVE_VERSE", instanceId: "local-hand-verse", playerId: MOCK_IDS.local }, mockCardDefinitionsById); expect(next.cardInstances["local-hand-verse"].zone).toBe("GRAVEYARD"); });
  it("supports tap, counters, sanctuary hp and field reorder", () => { let next = applyGameAction(buildMockGameState(), { type: "TAP_CARD", instanceId: "opponent-field-char" }); expect(next.cardInstances["opponent-field-char"].tapped).toBe(true); next = applyGameAction(next, { type: "UNTAP_CARD", instanceId: "opponent-field-char" }); next = applyGameAction(next, { type: "CHANGE_CARD_COUNTER", instanceId: "opponent-field-char", amount: 2 }); next = applyGameAction(next, { type: "CHANGE_SANCTUARY_HP", playerId: MOCK_IDS.local, amount: -3 }); expect(next.cardInstances["opponent-field-char"].counter).toBe(2); expect(next.players[MOCK_IDS.local].sanctuaryHp).toBe(19); });
});
