import { expect, test } from "@playwright/test";

test("two browser contexts share a private room and synchronize a draw", async ({ browser }) => {
  const contextA = await browser.newContext();
  const contextB = await browser.newContext();
  const pageA = await contextA.newPage();
  const pageB = await contextB.newPage();
  await pageA.goto("/");
  await pageA.getByPlaceholder("Tu nombre").fill("Alice");
  await pageA.getByRole("button", { name: "Crear sala" }).click();
  await expect(pageA).toHaveURL(/\/room\/[A-Z0-9]+/, { timeout: 30_000 });
  const roomUrl = pageA.url();
  await pageB.goto(roomUrl);
  await pageB.getByPlaceholder("Tu nombre").fill("Bob");
  await pageB.getByRole("button", { name: "Unirse" }).click();
  await expect(pageA.getByRole("heading", { name: "Preparar partida" })).toBeVisible({ timeout: 30_000 });
  await expect(pageB.getByRole("heading", { name: "Preparar partida" })).toBeVisible({ timeout: 30_000 });
  await pageA.getByRole("button", { name: "Usar deck de prueba" }).click();
  await pageB.getByRole("button", { name: "Usar deck de prueba" }).click();
  await pageA.getByRole("button", { name: "Enviar loadout" }).click();
  await pageB.getByRole("button", { name: "Enviar loadout" }).click();
  await expect(pageA.getByRole("heading", { name: "Orden privado de Esencias" })).toBeVisible({ timeout: 30_000 });
  await expect(pageB.getByRole("heading", { name: "Orden privado de Esencias" })).toBeVisible({ timeout: 30_000 });
  await pageA.getByRole("button", { name: "Confirmar orden" }).click();
  await pageB.getByRole("button", { name: "Confirmar orden" }).click();
  await expect(pageA.getByRole("heading", { name: "Mano inicial" })).toBeVisible({ timeout: 30_000 });
  await expect(pageB.getByRole("heading", { name: "Mano inicial" })).toBeVisible({ timeout: 30_000 });
  await pageA.getByRole("button", { name: "Continuar a Mulligan" }).click();
  await pageB.getByRole("button", { name: "Continuar a Mulligan" }).click();
  await expect(pageA.getByRole("button", { name: "MANTENER MANO" })).toBeVisible({ timeout: 30_000 });
  const mulliganSection = pageA.getByRole("heading", { name: "Mano inicial" }).locator("..").locator("..");
  const mulliganCards = mulliganSection.locator('[role="button"]');
  await expect(mulliganCards).toHaveCount(5);
  await mulliganCards.nth(0).click();
  await mulliganCards.nth(1).click();
  await pageA.getByRole("button", { name: "MULLIGAN 2" }).click();
  await expect(pageA.getByText("Decision confirmada. Esperando rival...")).toBeVisible();
  await pageB.getByRole("button", { name: "MANTENER MANO" }).click();
  await expect(pageA.getByText("Rev. 2")).toBeVisible();
  await expect(pageA.getByText("PV 22")).toBeVisible();
  await expect(pageB.getByText("PV 22")).toBeVisible();
  const activePage = await pageA.getByRole("button", { name: "Siguiente fase" }).isVisible() ? pageA : pageB;
  const rivalPage = activePage === pageA ? pageB : pageA;
  await activePage.getByRole("button", { name: "Siguiente fase" }).click();
  await expect(pageA.getByText("AMANECER")).toBeVisible();
  await expect(pageB.getByText("AMANECER")).toBeVisible();
  await activePage.getByRole("button", { name: "Siguiente fase" }).click();
  await expect(pageA.getByText("MEDIODIA")).toBeVisible();
  await expect(pageB.getByText("MEDIODIA")).toBeVisible();
  await activePage.getByRole("button", { name: "Siguiente fase" }).click();
  await expect(pageA.getByText("ANOCHECER")).toBeVisible();
  await expect(pageB.getByText("ANOCHECER")).toBeVisible();
  await activePage.getByRole("button", { name: "Terminar turno" }).click();
  await expect(pageA.getByText("ALBA")).toBeVisible();
  await expect(pageB.getByText("ALBA")).toBeVisible();
  await expect(rivalPage.getByRole("button", { name: "Siguiente fase" })).toBeVisible();
  const mainDeck = pageA.getByRole("button", { name: /Main Deck/ }).last();
  await mainDeck.click();
  await expect(pageA.getByText("Rev. 0")).toBeVisible();
  await mainDeck.click({ button: "right" });
  await pageA.getByRole("button", { name: "Robar" }).click();
  await expect(pageB.getByText("Rev. 7")).toBeVisible({ timeout: 30_000 });
  await expect(pageB.getByText(/Mano · 4/)).toBeVisible({ timeout: 30_000 });
  await pageA.reload();
  await expect(pageA.getByRole("button", { name: "Finalizar" })).toBeVisible({ timeout: 30_000 });
  await contextA.close();
  await contextB.close();
});
