"use client";

import { DndContext, DragEndEvent, DragOverlay, PointerSensor, useDraggable, useDroppable, useSensor, useSensors } from "@dnd-kit/core";
import { CSS } from "@dnd-kit/utilities";
import { useState } from "react";
import { mockCardDefinitionsById, MOCK_IDS, buildMockGameState } from "@/data/mock-card-catalog";
import { applyGameAction } from "@/domain/game/game.reducer";
import { getCardsInZone, sortHandForDisplay } from "@/domain/game/game.selectors";
import type { GameAction } from "@/domain/game/game.actions";
import type { CardInstance, CardZone } from "@/domain/game/game.types";
import { CardInspection } from "./CardInspection";
import { GameCard } from "./GameCard";

const local = MOCK_IDS.local;
function DropZone({ id, children, className = "" }: { id: string; children: React.ReactNode; className?: string }) { const { isOver, setNodeRef } = useDroppable({ id }); return <div ref={setNodeRef} className={`${className} ${isOver ? "bg-emerald-300/10 ring-1 ring-emerald-200/40" : ""}`}>{children}</div>; }
function DraggableCard({ card, definition, editable, onInspect, onDoubleClick, onContextMenu, onCounterChange, disabled }: { card: CardInstance; definition?: typeof mockCardDefinitionsById[string]; editable: boolean; onInspect: () => void; onDoubleClick: () => void; onContextMenu: (event: React.MouseEvent) => void; onCounterChange: (amount: number) => void; disabled?: boolean }) { const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({ id: card.instanceId, disabled }); return <div ref={setNodeRef} style={{ transform: CSS.Translate.toString(transform), opacity: isDragging ? 0.25 : 1 }} {...listeners} {...attributes}><GameCard card={card} definition={definition} editable={editable} onInspect={onInspect} onDoubleClick={onDoubleClick} onContextMenu={onContextMenu} onCounterChange={onCounterChange} /></div>; }

export function BoardSandbox() {
  const [state, setState] = useState(buildMockGameState);
  const [inspected, setInspected] = useState<CardInstance | null>(null);
  const [menu, setMenu] = useState<{ card: CardInstance; x: number; y: number } | null>(null);
  const [notice, setNotice] = useState("Arrastra cartas entre zonas para probar la estructura.");
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } }));
  const definitions = mockCardDefinitionsById;
  const localCards = (zone: CardZone) => getCardsInZone(state, zone, local);
  const opponentCards = (zone: CardZone) => getCardsInZone(state, zone, MOCK_IDS.opponent);
  const dispatch = (action: GameAction) => { try { setState((current) => applyGameAction(current, action, definitions)); setNotice(`Acción aplicada: ${action.type}`); } catch (error) { setNotice(error instanceof Error ? error.message : "Acción no disponible"); } };
  const inspect = (card: CardInstance) => setInspected(card);
  const cardDef = (card: CardInstance) => definitions[card.cardDefinitionId];
  const editable = (card: CardInstance) => card.controllerId === local;
  const handleDragEnd = ({ active, over }: DragEndEvent) => { if (!over) return; const card = state.cardInstances[String(active.id)]; const target = String(over.id); if (!card || !editable(card)) return; const definition = cardDef(card); if (target === "own-field" && card.zone === "HAND") { if (definition.type === "CHARACTER") dispatch({ type: "PLAY_CHARACTER", instanceId: card.instanceId, playerId: local }); if (definition.type === "RELIC") dispatch({ type: "PLAY_RELIC", instanceId: card.instanceId, playerId: local, attachedToInstanceId: null }); } else if (target === "verse-resolution" && card.zone === "HAND" && definition.type === "VERSE") dispatch({ type: "PLAY_VERSE", instanceId: card.instanceId, playerId: local }); else if (target === "own-graveyard" && (card.zone === "FIELD" || card.zone === "VERSE_RESOLUTION")) dispatch(card.zone === "VERSE_RESOLUTION" ? { type: "RESOLVE_VERSE", instanceId: card.instanceId, playerId: local } : { type: "MOVE_CARD", instanceId: card.instanceId, toZone: "GRAVEYARD", controllerId: local }); else if (target.startsWith("character:") && definition.type === "RELIC") { const characterId = target.slice(10); if (card.zone === "HAND") dispatch({ type: "PLAY_RELIC", instanceId: card.instanceId, playerId: local, attachedToInstanceId: characterId }); else if (card.zone === "FIELD") dispatch({ type: "ATTACH_RELIC", relicInstanceId: card.instanceId, characterInstanceId: characterId }); } else if (target.startsWith("character:") && definition.type === "CHARACTER" && card.zone === "FIELD") { const ordered = localCards("FIELD").filter((item) => cardDef(item).type === "CHARACTER").map((item) => item.instanceId); const targetIndex = ordered.indexOf(target.slice(10)); const currentIndex = ordered.indexOf(card.instanceId); if (targetIndex >= 0 && currentIndex >= 0) { ordered.splice(currentIndex, 1); ordered.splice(targetIndex, 0, card.instanceId); dispatch({ type: "REORDER_FIELD", playerId: local, orderedInstanceIds: ordered }); } } };
  const allField = localCards("FIELD");
  const characters = allField.filter((card) => cardDef(card).type === "CHARACTER");
  const looseRelics = allField.filter((card) => cardDef(card).type === "RELIC" && !card.attachedToInstanceId);
  const attached = (characterId: string) => allField.filter((card) => card.attachedToInstanceId === characterId);
  const renderCard = (card: CardInstance) => <DraggableCard key={card.instanceId} card={card} definition={cardDef(card)} editable={editable(card)} disabled={!editable(card) || card.zone === "ESSENCE_ZONE" || card.zone === "SANCTUARY"} onInspect={() => inspect(card)} onDoubleClick={() => dispatch({ type: card.tapped ? "UNTAP_CARD" : "TAP_CARD", instanceId: card.instanceId })} onContextMenu={(event) => { event.preventDefault(); setMenu({ card, x: event.clientX, y: event.clientY }); }} onCounterChange={(amount) => dispatch({ type: "CHANGE_CARD_COUNTER", instanceId: card.instanceId, amount })} />;
  return <DndContext sensors={sensors} onDragEnd={handleDragEnd}>
    <main className="min-h-screen bg-[#090807] p-3 text-zinc-100 md:p-6" onClick={() => setMenu(null)}>
      <header className="mx-auto mb-4 flex max-w-[1500px] flex-wrap items-center justify-between gap-3 border-b border-white/10 pb-3"><div><p className="text-[10px] uppercase tracking-[0.28em] text-amber-300/70">MISSION_001 / DEV BOARD</p><h1 className="text-xl font-semibold">Mesa de Crónicas</h1></div><div className="flex items-center gap-2 text-xs"><span className="border border-white/10 px-2 py-1 text-zinc-400">{state.phase}</span><button className="border border-emerald-300/40 px-3 py-1.5 text-emerald-100 hover:bg-emerald-300/10" onClick={() => dispatch({ type: "END_TURN" })}>Terminar turno</button></div></header>
      <section className="mx-auto flex max-w-[1500px] flex-col gap-3">
        <PlayerRow label="OPONENTE" cards={opponentCards("HAND")} field={opponentCards("FIELD")} sanctuaryHp={state.players[MOCK_IDS.opponent].sanctuaryHp} opponent renderCard={renderCard} />
        <DropZone id="verse-resolution" className="min-h-32 border border-rose-200/25 bg-rose-950/20 p-3"><div className="mb-2 flex items-center justify-between"><span className="text-xs uppercase tracking-[0.2em] text-rose-200/80">Verse Resolution</span><span className="text-xs text-zinc-500">{localCards("VERSE_RESOLUTION").length} en espera</span></div><div className="flex min-h-20 flex-wrap gap-3">{localCards("VERSE_RESOLUTION").map((card) => renderCard(card))}</div></DropZone>
        <div className="border-t border-white/10 pt-3"><div className="mb-2 flex items-center justify-between"><span className="text-xs uppercase tracking-[0.2em] text-emerald-200/70">Tu campo</span><span className="text-xs text-zinc-500">{notice}</span></div><DropZone id="own-field" className="min-h-44 border border-emerald-200/20 bg-emerald-950/10 p-3"><div className="flex flex-wrap items-start gap-4">{characters.map((card) => <DropZone key={card.instanceId} id={`character:${card.instanceId}`} className="min-h-36 border border-white/10 p-2"><div className="flex flex-col gap-2">{renderCard(card)}{attached(card.instanceId).map((relic) => <div key={relic.instanceId} className="ml-7">{renderCard(relic)}</div>)}</div></DropZone>)}{looseRelics.map((card) => renderCard(card))}</div></DropZone></div>
        <section className="grid grid-cols-[auto_1fr_auto_auto_auto] items-end gap-3 border-t border-white/10 pt-3"><DropZone id="own-graveyard" className="min-h-28 min-w-24 border border-white/10 bg-[#171311] p-2"><ZoneTitle title="Graveyard" count={localCards("GRAVEYARD").length} /><div className="flex gap-1">{localCards("GRAVEYARD").slice(-2).map((card) => <GameCard key={card.instanceId} card={card} definition={cardDef(card)} size="sm" />)}</div></DropZone><div><ZoneTitle title="Tu mano" count={localCards("HAND").length} /><div className="flex min-h-40 items-end overflow-x-auto px-5 pt-8">{sortHandForDisplay(localCards("HAND"), definitions).map((card, index) => <div key={card.instanceId} className="-ml-3 first:ml-0" style={{ transform: `rotate(${(index - 2) * 3}deg) translateY(${Math.abs(index - 2) * 2}px)` }}>{renderCard(card)}</div>)}</div></div><button className="border border-amber-200/30 bg-amber-200/10 px-3 py-2 text-xs text-amber-100" onClick={() => dispatch({ type: "DRAW_CARD", playerId: local })}>Robar<br />Main Deck</button><button className="border border-emerald-200/30 bg-emerald-200/10 px-3 py-2 text-xs text-emerald-100" onClick={() => dispatch({ type: "DRAW_ESSENCE", playerId: local })}>Robar<br />Essence</button><div className="border border-rose-200/30 bg-rose-950/30 p-2 text-center"><span className="text-[10px] uppercase text-rose-200/70">Santuario</span><strong className="block text-2xl">{state.players[local].sanctuaryHp}</strong><div className="flex gap-1"><button aria-label="Bajar vida" className="w-7 border border-white/15" onClick={() => dispatch({ type: "CHANGE_SANCTUARY_HP", playerId: local, amount: -1 })}>−</button><button aria-label="Subir vida" className="w-7 border border-white/15" onClick={() => dispatch({ type: "CHANGE_SANCTUARY_HP", playerId: local, amount: 1 })}>+</button></div></div></section>
      </section>
      {inspected && <CardInspection card={inspected} definition={cardDef(inspected)} onClose={() => setInspected(null)} />}
      {menu && <div className="fixed z-40 w-48 border border-white/15 bg-[#191513] p-1 text-xs shadow-2xl" style={{ left: menu.x, top: menu.y }} onClick={(event) => event.stopPropagation()}><button className="block w-full px-3 py-2 text-left hover:bg-white/10" onClick={() => { inspect(menu.card); setMenu(null); }}>Inspeccionar</button><button className="block w-full px-3 py-2 text-left hover:bg-white/10" onClick={() => { dispatch({ type: menu.card.tapped ? "UNTAP_CARD" : "TAP_CARD", instanceId: menu.card.instanceId }); setMenu(null); }}>{menu.card.tapped ? "Destapar" : "Girar"}</button><button className="block w-full px-3 py-2 text-left hover:bg-white/10" onClick={() => { dispatch({ type: menu.card.faceUp ? "FLIP_FACE_DOWN" : "FLIP_FACE_UP", instanceId: menu.card.instanceId }); setMenu(null); }}>Voltear</button></div>}
    </main><DragOverlay /></DndContext>;
}

function ZoneTitle({ title, count }: { title: string; count: number }) { return <div className="mb-2 flex items-center justify-between gap-2 text-[10px] uppercase tracking-widest text-zinc-500"><span>{title}</span><span>{count}</span></div>; }
function PlayerRow({ label, cards, field, sanctuaryHp, opponent, renderCard }: { label: string; cards: CardInstance[]; field: CardInstance[]; sanctuaryHp: number; opponent: boolean; renderCard: (card: CardInstance) => React.ReactNode }) { return <section className="border border-white/10 bg-[#100e0d] p-3"><div className="mb-2 flex justify-between text-xs text-zinc-500"><span>{label}</span><span>Santuario {sanctuaryHp}</span></div><div className="flex min-h-28 items-center gap-3"><div className="flex -space-x-8">{cards.slice(0, 6).map((card) => <GameCard key={card.instanceId} card={card} size="sm" />)}</div><div className="flex flex-1 flex-wrap gap-2">{field.map((card) => renderCard(card))}</div><span className="border border-white/10 px-3 py-8 text-xs text-zinc-500">{opponent ? "MAIN" : "DECK"}</span></div></section>; }
